[features]
seeds = false
skip-lint = false

[programs.localnet]
cat_sol20 = "3MyCiYPzAwJCgnPKiAYSb1TaVLZUYhe2YnHbBHw3F9V5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ace/.config/solana/id.json"
