[features]
seeds = false
skip-lint = false
[programs.localnet]
cat_sol721 = "6fi6yXzAnknteN94jJ9iZWjpMBSxp1NdADrqApgW7dV6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ace/.config/solana/id.json"
