[features]
seeds = false
skip-lint = false
[programs.localnet]
cat_sol20 = "3MyCiYPzAwJCgnPKiAYSb1TaVLZUYhe2YnHbBHw3F9V5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ace/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
