[features]
seeds = false
skip-lint = false

[programs.localnet]
cat_sol20 = "9oMo3tUy3gBYi9FHEDF8YFQBryiUXLqq8wi4Ztsd186Y"
cat_sol20_proxy = "CnKFjQSLcPMVhmy8GzcetJE7dyDXqhsNaPHZzPtQ87oD"
test_token = "6sFFctSuHcmuxVnFtpeeGq4b5udhhvyqah2K3yDuq3Q1"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ace/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"