[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
cat_sol20 = "Dw4ev4agC4ZYxi1HUJtruS4xWij5iMQxijLX4J7coC4q"
cat_sol20_proxy = "JA3FctHbRBoDtdiw8PaVFosGt6KYDKqA42St7pr9DQzb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ace/.config/solana/id.json"
