[features]
seeds = false
skip-lint = false
[programs.localnet]
spl_cat = "bhp6ce99vHEbpzRjUtpkLQpDQmzbHU5DFBX4pNLVrzb"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ace/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
