[features]
seeds = false
skip-lint = false
[programs.localnet]
cat_sol721 = "CknPdA3Ete1m1RuNSKgeSekBaZDd9m9gC8wQU88U5VB4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ace/.config/solana/id.json"
