[features]
seeds = false
skip-lint = false
[programs.localnet]
cat_sol20 = "q4hdc3QA2up4ewqKemn8TUit6ki2BZFjcwVMGe6jfQd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ace/.config/solana/id.json"
