[features]
seeds = false
skip-lint = false
[programs.localnet]
cat_sol20 = "65dnUJXdYiKuMUBYyMTowK5g8MzNhABeeTzCtMg1RodQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ace/.config/solana/id.json"
